version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/annihilatorrrr/goshort"

[[transformers]]
name = "gofmt"
enabled = true

[[transformers]]
name = "gofumpt"
enabled = true

[[analyzers]]
name = "javascript"

[[transformers]]
name = "standardjs"

[[transformers]]
name = "prettier"
